image: openjdk:8-jdk

variables:
  LINSTOR_CONTROLLER_HOST: 'linstor-controller'
  LINSTOR_CONTROLLER_PORT: '3370'

services:
  - name: $CI_REGISTRY/linstor/linstor-server/controller
    alias: linstor-controller

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - |
      curl -X POST -H "Content-Type: application/json" -d '{"resource_definition": {"name": "rsc-restart"}}' http://linstor-controller:3370/v1/resource-definitions
      curl -X POST -H "Content-Type: application/json" -d '{"volume_definition": {"size_kib": 104857600, "flags": []}, "drbd_minor_number": 1002}' http://linstor-controller:3370/v1/resource-definitions/rsc-restart/volume-definitions
    - JAVA_OPTS="-ea" ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
