/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.10.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BackupAbort
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-31T11:02:45.596Z[GMT]")
public class BackupAbort {
  @JsonProperty("rsc_name")
  private String rscName = null;

  @JsonProperty("restore")
  private Boolean restore = null;

  @JsonProperty("create")
  private Boolean create = null;

  public BackupAbort rscName(String rscName) {
    this.rscName = rscName;
    return this;
  }

   /**
   * Get rscName
   * @return rscName
  **/
  @Schema(description = "")
  public String getRscName() {
    return rscName;
  }

  public void setRscName(String rscName) {
    this.rscName = rscName;
  }

  public BackupAbort restore(Boolean restore) {
    this.restore = restore;
    return this;
  }

   /**
   * Get restore
   * @return restore
  **/
  @Schema(description = "")
  public Boolean isRestore() {
    return restore;
  }

  public void setRestore(Boolean restore) {
    this.restore = restore;
  }

  public BackupAbort create(Boolean create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  @Schema(description = "")
  public Boolean isCreate() {
    return create;
  }

  public void setCreate(Boolean create) {
    this.create = create;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupAbort backupAbort = (BackupAbort) o;
    return Objects.equals(this.rscName, backupAbort.rscName) &&
        Objects.equals(this.restore, backupAbort.restore) &&
        Objects.equals(this.create, backupAbort.create);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rscName, restore, create);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupAbort {\n");
    
    sb.append("    rscName: ").append(toIndentedString(rscName)).append("\n");
    sb.append("    restore: ").append(toIndentedString(restore)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
