/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.10.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.BackupS3;
import com.linbit.linstor.api.model.BackupVolumes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Backup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-31T11:02:45.596Z[GMT]")
public class Backup {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("start_time")
  private String startTime = null;

  @JsonProperty("start_timestamp")
  private Long startTimestamp = null;

  @JsonProperty("finished_time")
  private String finishedTime = null;

  @JsonProperty("finished_timestamp")
  private Long finishedTimestamp = null;

  @JsonProperty("origin_rsc")
  private String originRsc = null;

  @JsonProperty("origin_node")
  private String originNode = null;

  @JsonProperty("fail_messages")
  private String failMessages = null;

  @JsonProperty("vlms")
  private List<BackupVolumes> vlms = null;

  @JsonProperty("success")
  private Boolean success = null;

  @JsonProperty("shipping")
  private Boolean shipping = null;

  @JsonProperty("restorable")
  private Boolean restorable = null;

  @JsonProperty("s3")
  private BackupS3 s3 = null;

  @JsonProperty("based_on_id")
  private String basedOnId = null;

  public Backup id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Backup startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(description = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public Backup startTimestamp(Long startTimestamp) {
    this.startTimestamp = startTimestamp;
    return this;
  }

   /**
   * Get startTimestamp
   * @return startTimestamp
  **/
  @Schema(description = "")
  public Long getStartTimestamp() {
    return startTimestamp;
  }

  public void setStartTimestamp(Long startTimestamp) {
    this.startTimestamp = startTimestamp;
  }

  public Backup finishedTime(String finishedTime) {
    this.finishedTime = finishedTime;
    return this;
  }

   /**
   * Get finishedTime
   * @return finishedTime
  **/
  @Schema(description = "")
  public String getFinishedTime() {
    return finishedTime;
  }

  public void setFinishedTime(String finishedTime) {
    this.finishedTime = finishedTime;
  }

  public Backup finishedTimestamp(Long finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
    return this;
  }

   /**
   * Get finishedTimestamp
   * @return finishedTimestamp
  **/
  @Schema(description = "")
  public Long getFinishedTimestamp() {
    return finishedTimestamp;
  }

  public void setFinishedTimestamp(Long finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
  }

  public Backup originRsc(String originRsc) {
    this.originRsc = originRsc;
    return this;
  }

   /**
   * Get originRsc
   * @return originRsc
  **/
  @Schema(description = "")
  public String getOriginRsc() {
    return originRsc;
  }

  public void setOriginRsc(String originRsc) {
    this.originRsc = originRsc;
  }

  public Backup originNode(String originNode) {
    this.originNode = originNode;
    return this;
  }

   /**
   * Get originNode
   * @return originNode
  **/
  @Schema(description = "")
  public String getOriginNode() {
    return originNode;
  }

  public void setOriginNode(String originNode) {
    this.originNode = originNode;
  }

  public Backup failMessages(String failMessages) {
    this.failMessages = failMessages;
    return this;
  }

   /**
   * Get failMessages
   * @return failMessages
  **/
  @Schema(description = "")
  public String getFailMessages() {
    return failMessages;
  }

  public void setFailMessages(String failMessages) {
    this.failMessages = failMessages;
  }

  public Backup vlms(List<BackupVolumes> vlms) {
    this.vlms = vlms;
    return this;
  }

  public Backup addVlmsItem(BackupVolumes vlmsItem) {
    if (this.vlms == null) {
      this.vlms = new ArrayList<>();
    }
    this.vlms.add(vlmsItem);
    return this;
  }

   /**
   * Get vlms
   * @return vlms
  **/
  @Schema(description = "")
  public List<BackupVolumes> getVlms() {
    return vlms;
  }

  public void setVlms(List<BackupVolumes> vlms) {
    this.vlms = vlms;
  }

  public Backup success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @Schema(description = "")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public Backup shipping(Boolean shipping) {
    this.shipping = shipping;
    return this;
  }

   /**
   * Get shipping
   * @return shipping
  **/
  @Schema(description = "")
  public Boolean isShipping() {
    return shipping;
  }

  public void setShipping(Boolean shipping) {
    this.shipping = shipping;
  }

  public Backup restorable(Boolean restorable) {
    this.restorable = restorable;
    return this;
  }

   /**
   * Get restorable
   * @return restorable
  **/
  @Schema(description = "")
  public Boolean isRestorable() {
    return restorable;
  }

  public void setRestorable(Boolean restorable) {
    this.restorable = restorable;
  }

  public Backup s3(BackupS3 s3) {
    this.s3 = s3;
    return this;
  }

   /**
   * Get s3
   * @return s3
  **/
  @Schema(description = "")
  public BackupS3 getS3() {
    return s3;
  }

  public void setS3(BackupS3 s3) {
    this.s3 = s3;
  }

  public Backup basedOnId(String basedOnId) {
    this.basedOnId = basedOnId;
    return this;
  }

   /**
   * Get basedOnId
   * @return basedOnId
  **/
  @Schema(description = "")
  public String getBasedOnId() {
    return basedOnId;
  }

  public void setBasedOnId(String basedOnId) {
    this.basedOnId = basedOnId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Backup backup = (Backup) o;
    return Objects.equals(this.id, backup.id) &&
        Objects.equals(this.startTime, backup.startTime) &&
        Objects.equals(this.startTimestamp, backup.startTimestamp) &&
        Objects.equals(this.finishedTime, backup.finishedTime) &&
        Objects.equals(this.finishedTimestamp, backup.finishedTimestamp) &&
        Objects.equals(this.originRsc, backup.originRsc) &&
        Objects.equals(this.originNode, backup.originNode) &&
        Objects.equals(this.failMessages, backup.failMessages) &&
        Objects.equals(this.vlms, backup.vlms) &&
        Objects.equals(this.success, backup.success) &&
        Objects.equals(this.shipping, backup.shipping) &&
        Objects.equals(this.restorable, backup.restorable) &&
        Objects.equals(this.s3, backup.s3) &&
        Objects.equals(this.basedOnId, backup.basedOnId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startTime, startTimestamp, finishedTime, finishedTimestamp, originRsc, originNode, failMessages, vlms, success, shipping, restorable, s3, basedOnId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Backup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    startTimestamp: ").append(toIndentedString(startTimestamp)).append("\n");
    sb.append("    finishedTime: ").append(toIndentedString(finishedTime)).append("\n");
    sb.append("    finishedTimestamp: ").append(toIndentedString(finishedTimestamp)).append("\n");
    sb.append("    originRsc: ").append(toIndentedString(originRsc)).append("\n");
    sb.append("    originNode: ").append(toIndentedString(originNode)).append("\n");
    sb.append("    failMessages: ").append(toIndentedString(failMessages)).append("\n");
    sb.append("    vlms: ").append(toIndentedString(vlms)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    shipping: ").append(toIndentedString(shipping)).append("\n");
    sb.append("    restorable: ").append(toIndentedString(restorable)).append("\n");
    sb.append("    s3: ").append(toIndentedString(s3)).append("\n");
    sb.append("    basedOnId: ").append(toIndentedString(basedOnId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
