/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.Backup;
import com.linbit.linstor.api.model.BackupOther;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * BackupList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class BackupList {
  @JsonProperty("linstor")
  private Map<String, Backup> linstor = null;

  @JsonProperty("other")
  private BackupOther other = null;

  public BackupList linstor(Map<String, Backup> linstor) {
    this.linstor = linstor;
    return this;
  }

  public BackupList putLinstorItem(String key, Backup linstorItem) {
    if (this.linstor == null) {
      this.linstor = new HashMap<>();
    }
    this.linstor.put(key, linstorItem);
    return this;
  }

   /**
   * A list containing all entries found that are or could be from linstor
   * @return linstor
  **/
  @Schema(description = "A list containing all entries found that are or could be from linstor")
  public Map<String, Backup> getLinstor() {
    return linstor;
  }

  public void setLinstor(Map<String, Backup> linstor) {
    this.linstor = linstor;
  }

  public BackupList other(BackupOther other) {
    this.other = other;
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @Schema(description = "")
  public BackupOther getOther() {
    return other;
  }

  public void setOther(BackupOther other) {
    this.other = other;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupList backupList = (BackupList) o;
    return Objects.equals(this.linstor, backupList.linstor) &&
        Objects.equals(this.other, backupList.other);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linstor, other);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupList {\n");
    
    sb.append("    linstor: ").append(toIndentedString(linstor)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
