/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.NodeQueue;
import com.linbit.linstor.api.model.SnapQueue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * BackupQueues
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class BackupQueues {
  @JsonProperty("node_queues")
  private List<NodeQueue> nodeQueues = null;

  @JsonProperty("snap_queues")
  private List<SnapQueue> snapQueues = null;

  public BackupQueues nodeQueues(List<NodeQueue> nodeQueues) {
    this.nodeQueues = nodeQueues;
    return this;
  }

  public BackupQueues addNodeQueuesItem(NodeQueue nodeQueuesItem) {
    if (this.nodeQueues == null) {
      this.nodeQueues = new ArrayList<>();
    }
    this.nodeQueues.add(nodeQueuesItem);
    return this;
  }

   /**
   * All nodes with a list of queued snapshots. Will be empty if snap_queues is set 
   * @return nodeQueues
  **/
  @Schema(description = "All nodes with a list of queued snapshots. Will be empty if snap_queues is set ")
  public List<NodeQueue> getNodeQueues() {
    return nodeQueues;
  }

  public void setNodeQueues(List<NodeQueue> nodeQueues) {
    this.nodeQueues = nodeQueues;
  }

  public BackupQueues snapQueues(List<SnapQueue> snapQueues) {
    this.snapQueues = snapQueues;
    return this;
  }

  public BackupQueues addSnapQueuesItem(SnapQueue snapQueuesItem) {
    if (this.snapQueues == null) {
      this.snapQueues = new ArrayList<>();
    }
    this.snapQueues.add(snapQueuesItem);
    return this;
  }

   /**
   * All snapshots with a list of nodes they are queued on. Will be empty if node_queues is set 
   * @return snapQueues
  **/
  @Schema(description = "All snapshots with a list of nodes they are queued on. Will be empty if node_queues is set ")
  public List<SnapQueue> getSnapQueues() {
    return snapQueues;
  }

  public void setSnapQueues(List<SnapQueue> snapQueues) {
    this.snapQueues = snapQueues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupQueues backupQueues = (BackupQueues) o;
    return Objects.equals(this.nodeQueues, backupQueues.nodeQueues) &&
        Objects.equals(this.snapQueues, backupQueues.snapQueues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeQueues, snapQueues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupQueues {\n");
    
    sb.append("    nodeQueues: ").append(toIndentedString(nodeQueues)).append("\n");
    sb.append("    snapQueues: ").append(toIndentedString(snapQueues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
