/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.24.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.BackupVolumesS3;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BackupVolumes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-18T06:34:31.141535853Z[Etc/UTC]")

public class BackupVolumes {
  @JsonProperty("vlm_nr")
  private Long vlmNr = null;

  @JsonProperty("finished_time")
  private String finishedTime = null;

  @JsonProperty("finished_timestamp")
  private Long finishedTimestamp = null;

  @JsonProperty("s3")
  private BackupVolumesS3 s3 = null;

  public BackupVolumes vlmNr(Long vlmNr) {
    this.vlmNr = vlmNr;
    return this;
  }

   /**
   * Get vlmNr
   * @return vlmNr
  **/
  @Schema(required = true, description = "")
  public Long getVlmNr() {
    return vlmNr;
  }

  public void setVlmNr(Long vlmNr) {
    this.vlmNr = vlmNr;
  }

  public BackupVolumes finishedTime(String finishedTime) {
    this.finishedTime = finishedTime;
    return this;
  }

   /**
   * Get finishedTime
   * @return finishedTime
  **/
  @Schema(description = "")
  public String getFinishedTime() {
    return finishedTime;
  }

  public void setFinishedTime(String finishedTime) {
    this.finishedTime = finishedTime;
  }

  public BackupVolumes finishedTimestamp(Long finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
    return this;
  }

   /**
   * Get finishedTimestamp
   * @return finishedTimestamp
  **/
  @Schema(description = "")
  public Long getFinishedTimestamp() {
    return finishedTimestamp;
  }

  public void setFinishedTimestamp(Long finishedTimestamp) {
    this.finishedTimestamp = finishedTimestamp;
  }

  public BackupVolumes s3(BackupVolumesS3 s3) {
    this.s3 = s3;
    return this;
  }

   /**
   * Get s3
   * @return s3
  **/
  @Schema(description = "")
  public BackupVolumesS3 getS3() {
    return s3;
  }

  public void setS3(BackupVolumesS3 s3) {
    this.s3 = s3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupVolumes backupVolumes = (BackupVolumes) o;
    return Objects.equals(this.vlmNr, backupVolumes.vlmNr) &&
        Objects.equals(this.finishedTime, backupVolumes.finishedTime) &&
        Objects.equals(this.finishedTimestamp, backupVolumes.finishedTimestamp) &&
        Objects.equals(this.s3, backupVolumes.s3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vlmNr, finishedTime, finishedTimestamp, s3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupVolumes {\n");
    
    sb.append("    vlmNr: ").append(toIndentedString(vlmNr)).append("\n");
    sb.append("    finishedTime: ").append(toIndentedString(finishedTime)).append("\n");
    sb.append("    finishedTimestamp: ").append(toIndentedString(finishedTimestamp)).append("\n");
    sb.append("    s3: ").append(toIndentedString(s3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
