/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.20.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.BackupInfoStorPool;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * BackupInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-03T09:13:01.489Z[GMT]")

public class BackupInfo {
  @JsonProperty("rsc")
  private String rsc = null;

  @JsonProperty("full")
  private String full = null;

  @JsonProperty("snap")
  private String snap = null;

  @JsonProperty("latest")
  private String latest = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("dl_size_kib")
  private Long dlSizeKib = null;

  @JsonProperty("alloc_size_kib")
  private Long allocSizeKib = null;

  @JsonProperty("storpools")
  private List<BackupInfoStorPool> storpools = new ArrayList<>();

  public BackupInfo rsc(String rsc) {
    this.rsc = rsc;
    return this;
  }

   /**
   * Get rsc
   * @return rsc
  **/
  @Schema(required = true, description = "")
  public String getRsc() {
    return rsc;
  }

  public void setRsc(String rsc) {
    this.rsc = rsc;
  }

  public BackupInfo full(String full) {
    this.full = full;
    return this;
  }

   /**
   * Get full
   * @return full
  **/
  @Schema(required = true, description = "")
  public String getFull() {
    return full;
  }

  public void setFull(String full) {
    this.full = full;
  }

  public BackupInfo snap(String snap) {
    this.snap = snap;
    return this;
  }

   /**
   * Get snap
   * @return snap
  **/
  @Schema(description = "")
  public String getSnap() {
    return snap;
  }

  public void setSnap(String snap) {
    this.snap = snap;
  }

  public BackupInfo latest(String latest) {
    this.latest = latest;
    return this;
  }

   /**
   * Get latest
   * @return latest
  **/
  @Schema(required = true, description = "")
  public String getLatest() {
    return latest;
  }

  public void setLatest(String latest) {
    this.latest = latest;
  }

  public BackupInfo count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public BackupInfo dlSizeKib(Long dlSizeKib) {
    this.dlSizeKib = dlSizeKib;
    return this;
  }

   /**
   * Get dlSizeKib
   * @return dlSizeKib
  **/
  @Schema(required = true, description = "")
  public Long getDlSizeKib() {
    return dlSizeKib;
  }

  public void setDlSizeKib(Long dlSizeKib) {
    this.dlSizeKib = dlSizeKib;
  }

  public BackupInfo allocSizeKib(Long allocSizeKib) {
    this.allocSizeKib = allocSizeKib;
    return this;
  }

   /**
   * Get allocSizeKib
   * @return allocSizeKib
  **/
  @Schema(required = true, description = "")
  public Long getAllocSizeKib() {
    return allocSizeKib;
  }

  public void setAllocSizeKib(Long allocSizeKib) {
    this.allocSizeKib = allocSizeKib;
  }

  public BackupInfo storpools(List<BackupInfoStorPool> storpools) {
    this.storpools = storpools;
    return this;
  }

  public BackupInfo addStorpoolsItem(BackupInfoStorPool storpoolsItem) {
    this.storpools.add(storpoolsItem);
    return this;
  }

   /**
   * Get storpools
   * @return storpools
  **/
  @Schema(required = true, description = "")
  public List<BackupInfoStorPool> getStorpools() {
    return storpools;
  }

  public void setStorpools(List<BackupInfoStorPool> storpools) {
    this.storpools = storpools;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupInfo backupInfo = (BackupInfo) o;
    return Objects.equals(this.rsc, backupInfo.rsc) &&
        Objects.equals(this.full, backupInfo.full) &&
        Objects.equals(this.snap, backupInfo.snap) &&
        Objects.equals(this.latest, backupInfo.latest) &&
        Objects.equals(this.count, backupInfo.count) &&
        Objects.equals(this.dlSizeKib, backupInfo.dlSizeKib) &&
        Objects.equals(this.allocSizeKib, backupInfo.allocSizeKib) &&
        Objects.equals(this.storpools, backupInfo.storpools);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rsc, full, snap, latest, count, dlSizeKib, allocSizeKib, storpools);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupInfo {\n");
    
    sb.append("    rsc: ").append(toIndentedString(rsc)).append("\n");
    sb.append("    full: ").append(toIndentedString(full)).append("\n");
    sb.append("    snap: ").append(toIndentedString(snap)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    dlSizeKib: ").append(toIndentedString(dlSizeKib)).append("\n");
    sb.append("    allocSizeKib: ").append(toIndentedString(allocSizeKib)).append("\n");
    sb.append("    storpools: ").append(toIndentedString(storpools)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
