/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.6.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ControllerConfigLdap
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-05T10:27:33.226Z[GMT]")
public class ControllerConfigLdap {
  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("public_access_allowed")
  private Boolean publicAccessAllowed = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("dn")
  private String dn = null;

  @JsonProperty("search_base")
  private String searchBase = null;

  @JsonProperty("search_filter")
  private String searchFilter = null;

  public ControllerConfigLdap enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @Schema(description = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ControllerConfigLdap publicAccessAllowed(Boolean publicAccessAllowed) {
    this.publicAccessAllowed = publicAccessAllowed;
    return this;
  }

   /**
   * Get publicAccessAllowed
   * @return publicAccessAllowed
  **/
  @Schema(description = "")
  public Boolean isPublicAccessAllowed() {
    return publicAccessAllowed;
  }

  public void setPublicAccessAllowed(Boolean publicAccessAllowed) {
    this.publicAccessAllowed = publicAccessAllowed;
  }

  public ControllerConfigLdap uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public ControllerConfigLdap dn(String dn) {
    this.dn = dn;
    return this;
  }

   /**
   * Get dn
   * @return dn
  **/
  @Schema(description = "")
  public String getDn() {
    return dn;
  }

  public void setDn(String dn) {
    this.dn = dn;
  }

  public ControllerConfigLdap searchBase(String searchBase) {
    this.searchBase = searchBase;
    return this;
  }

   /**
   * Get searchBase
   * @return searchBase
  **/
  @Schema(description = "")
  public String getSearchBase() {
    return searchBase;
  }

  public void setSearchBase(String searchBase) {
    this.searchBase = searchBase;
  }

  public ControllerConfigLdap searchFilter(String searchFilter) {
    this.searchFilter = searchFilter;
    return this;
  }

   /**
   * Get searchFilter
   * @return searchFilter
  **/
  @Schema(description = "")
  public String getSearchFilter() {
    return searchFilter;
  }

  public void setSearchFilter(String searchFilter) {
    this.searchFilter = searchFilter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerConfigLdap controllerConfigLdap = (ControllerConfigLdap) o;
    return Objects.equals(this.enabled, controllerConfigLdap.enabled) &&
        Objects.equals(this.publicAccessAllowed, controllerConfigLdap.publicAccessAllowed) &&
        Objects.equals(this.uri, controllerConfigLdap.uri) &&
        Objects.equals(this.dn, controllerConfigLdap.dn) &&
        Objects.equals(this.searchBase, controllerConfigLdap.searchBase) &&
        Objects.equals(this.searchFilter, controllerConfigLdap.searchFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, publicAccessAllowed, uri, dn, searchBase, searchFilter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerConfigLdap {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    publicAccessAllowed: ").append(toIndentedString(publicAccessAllowed)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    dn: ").append(toIndentedString(dn)).append("\n");
    sb.append("    searchBase: ").append(toIndentedString(searchBase)).append("\n");
    sb.append("    searchFilter: ").append(toIndentedString(searchFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
