/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.22.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.ControllerConfigDbEtcd;
import com.linbit.linstor.api.model.ControllerConfigDbK8s;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ControllerConfigDb
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-02T13:40:09.628252133Z[Etc/UTC]")

public class ControllerConfigDb {
  @JsonProperty("connection_url")
  private String connectionUrl = null;

  @JsonProperty("ca_certificate")
  private String caCertificate = null;

  @JsonProperty("client_certificate")
  private String clientCertificate = null;

  @JsonProperty("in_memory")
  private String inMemory = null;

  @JsonProperty("version_check_disabled")
  private Boolean versionCheckDisabled = null;

  @JsonProperty("etcd")
  private ControllerConfigDbEtcd etcd = null;

  @JsonProperty("k8s")
  private ControllerConfigDbK8s k8s = null;

  public ControllerConfigDb connectionUrl(String connectionUrl) {
    this.connectionUrl = connectionUrl;
    return this;
  }

   /**
   * Get connectionUrl
   * @return connectionUrl
  **/
  @Schema(description = "")
  public String getConnectionUrl() {
    return connectionUrl;
  }

  public void setConnectionUrl(String connectionUrl) {
    this.connectionUrl = connectionUrl;
  }

  public ControllerConfigDb caCertificate(String caCertificate) {
    this.caCertificate = caCertificate;
    return this;
  }

   /**
   * Get caCertificate
   * @return caCertificate
  **/
  @Schema(description = "")
  public String getCaCertificate() {
    return caCertificate;
  }

  public void setCaCertificate(String caCertificate) {
    this.caCertificate = caCertificate;
  }

  public ControllerConfigDb clientCertificate(String clientCertificate) {
    this.clientCertificate = clientCertificate;
    return this;
  }

   /**
   * Get clientCertificate
   * @return clientCertificate
  **/
  @Schema(description = "")
  public String getClientCertificate() {
    return clientCertificate;
  }

  public void setClientCertificate(String clientCertificate) {
    this.clientCertificate = clientCertificate;
  }

  public ControllerConfigDb inMemory(String inMemory) {
    this.inMemory = inMemory;
    return this;
  }

   /**
   * Get inMemory
   * @return inMemory
  **/
  @Schema(description = "")
  public String getInMemory() {
    return inMemory;
  }

  public void setInMemory(String inMemory) {
    this.inMemory = inMemory;
  }

  public ControllerConfigDb versionCheckDisabled(Boolean versionCheckDisabled) {
    this.versionCheckDisabled = versionCheckDisabled;
    return this;
  }

   /**
   * Get versionCheckDisabled
   * @return versionCheckDisabled
  **/
  @Schema(description = "")
  public Boolean isVersionCheckDisabled() {
    return versionCheckDisabled;
  }

  public void setVersionCheckDisabled(Boolean versionCheckDisabled) {
    this.versionCheckDisabled = versionCheckDisabled;
  }

  public ControllerConfigDb etcd(ControllerConfigDbEtcd etcd) {
    this.etcd = etcd;
    return this;
  }

   /**
   * Get etcd
   * @return etcd
  **/
  @Schema(description = "")
  public ControllerConfigDbEtcd getEtcd() {
    return etcd;
  }

  public void setEtcd(ControllerConfigDbEtcd etcd) {
    this.etcd = etcd;
  }

  public ControllerConfigDb k8s(ControllerConfigDbK8s k8s) {
    this.k8s = k8s;
    return this;
  }

   /**
   * Get k8s
   * @return k8s
  **/
  @Schema(description = "")
  public ControllerConfigDbK8s getK8s() {
    return k8s;
  }

  public void setK8s(ControllerConfigDbK8s k8s) {
    this.k8s = k8s;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerConfigDb controllerConfigDb = (ControllerConfigDb) o;
    return Objects.equals(this.connectionUrl, controllerConfigDb.connectionUrl) &&
        Objects.equals(this.caCertificate, controllerConfigDb.caCertificate) &&
        Objects.equals(this.clientCertificate, controllerConfigDb.clientCertificate) &&
        Objects.equals(this.inMemory, controllerConfigDb.inMemory) &&
        Objects.equals(this.versionCheckDisabled, controllerConfigDb.versionCheckDisabled) &&
        Objects.equals(this.etcd, controllerConfigDb.etcd) &&
        Objects.equals(this.k8s, controllerConfigDb.k8s);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectionUrl, caCertificate, clientCertificate, inMemory, versionCheckDisabled, etcd, k8s);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerConfigDb {\n");
    
    sb.append("    connectionUrl: ").append(toIndentedString(connectionUrl)).append("\n");
    sb.append("    caCertificate: ").append(toIndentedString(caCertificate)).append("\n");
    sb.append("    clientCertificate: ").append(toIndentedString(clientCertificate)).append("\n");
    sb.append("    inMemory: ").append(toIndentedString(inMemory)).append("\n");
    sb.append("    versionCheckDisabled: ").append(toIndentedString(versionCheckDisabled)).append("\n");
    sb.append("    etcd: ").append(toIndentedString(etcd)).append("\n");
    sb.append("    k8s: ").append(toIndentedString(k8s)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
