/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.10.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DrbdVolumeDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-31T11:02:45.596Z[GMT]")
public class DrbdVolumeDefinition implements OneOfVolumeDefinitionLayerData {
  @JsonProperty("resource_name_suffix")
  private String resourceNameSuffix = null;

  @JsonProperty("volume_number")
  private Integer volumeNumber = null;

  @JsonProperty("minor_number")
  private Integer minorNumber = null;

  public DrbdVolumeDefinition resourceNameSuffix(String resourceNameSuffix) {
    this.resourceNameSuffix = resourceNameSuffix;
    return this;
  }

   /**
   * Get resourceNameSuffix
   * @return resourceNameSuffix
  **/
  @Schema(description = "")
  public String getResourceNameSuffix() {
    return resourceNameSuffix;
  }

  public void setResourceNameSuffix(String resourceNameSuffix) {
    this.resourceNameSuffix = resourceNameSuffix;
  }

  public DrbdVolumeDefinition volumeNumber(Integer volumeNumber) {
    this.volumeNumber = volumeNumber;
    return this;
  }

   /**
   * Get volumeNumber
   * @return volumeNumber
  **/
  @Schema(description = "")
  public Integer getVolumeNumber() {
    return volumeNumber;
  }

  public void setVolumeNumber(Integer volumeNumber) {
    this.volumeNumber = volumeNumber;
  }

  public DrbdVolumeDefinition minorNumber(Integer minorNumber) {
    this.minorNumber = minorNumber;
    return this;
  }

   /**
   * Get minorNumber
   * @return minorNumber
  **/
  @Schema(description = "")
  public Integer getMinorNumber() {
    return minorNumber;
  }

  public void setMinorNumber(Integer minorNumber) {
    this.minorNumber = minorNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrbdVolumeDefinition drbdVolumeDefinition = (DrbdVolumeDefinition) o;
    return Objects.equals(this.resourceNameSuffix, drbdVolumeDefinition.resourceNameSuffix) &&
        Objects.equals(this.volumeNumber, drbdVolumeDefinition.volumeNumber) &&
        Objects.equals(this.minorNumber, drbdVolumeDefinition.minorNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceNameSuffix, volumeNumber, minorNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrbdVolumeDefinition {\n");
    
    sb.append("    resourceNameSuffix: ").append(toIndentedString(resourceNameSuffix)).append("\n");
    sb.append("    volumeNumber: ").append(toIndentedString(volumeNumber)).append("\n");
    sb.append("    minorNumber: ").append(toIndentedString(minorNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
