/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.20.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EXOS enclosure name, controller IPs and health status
 */
@Schema(description = "EXOS enclosure name, controller IPs and health status")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-03T09:13:01.489Z[GMT]")

public class ExosEnclosureHealth {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("ctrl_a_ip")
  private String ctrlAIp = null;

  @JsonProperty("ctrl_b_ip")
  private String ctrlBIp = null;

  @JsonProperty("health")
  private String health = null;

  @JsonProperty("health_reason")
  private String healthReason = null;

  public ExosEnclosureHealth name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExosEnclosureHealth ctrlAIp(String ctrlAIp) {
    this.ctrlAIp = ctrlAIp;
    return this;
  }

   /**
   * Get ctrlAIp
   * @return ctrlAIp
  **/
  @Schema(description = "")
  public String getCtrlAIp() {
    return ctrlAIp;
  }

  public void setCtrlAIp(String ctrlAIp) {
    this.ctrlAIp = ctrlAIp;
  }

  public ExosEnclosureHealth ctrlBIp(String ctrlBIp) {
    this.ctrlBIp = ctrlBIp;
    return this;
  }

   /**
   * Get ctrlBIp
   * @return ctrlBIp
  **/
  @Schema(description = "")
  public String getCtrlBIp() {
    return ctrlBIp;
  }

  public void setCtrlBIp(String ctrlBIp) {
    this.ctrlBIp = ctrlBIp;
  }

  public ExosEnclosureHealth health(String health) {
    this.health = health;
    return this;
  }

   /**
   * Get health
   * @return health
  **/
  @Schema(description = "")
  public String getHealth() {
    return health;
  }

  public void setHealth(String health) {
    this.health = health;
  }

  public ExosEnclosureHealth healthReason(String healthReason) {
    this.healthReason = healthReason;
    return this;
  }

   /**
   * Get healthReason
   * @return healthReason
  **/
  @Schema(description = "")
  public String getHealthReason() {
    return healthReason;
  }

  public void setHealthReason(String healthReason) {
    this.healthReason = healthReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExosEnclosureHealth exosEnclosureHealth = (ExosEnclosureHealth) o;
    return Objects.equals(this.name, exosEnclosureHealth.name) &&
        Objects.equals(this.ctrlAIp, exosEnclosureHealth.ctrlAIp) &&
        Objects.equals(this.ctrlBIp, exosEnclosureHealth.ctrlBIp) &&
        Objects.equals(this.health, exosEnclosureHealth.health) &&
        Objects.equals(this.healthReason, exosEnclosureHealth.healthReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ctrlAIp, ctrlBIp, health, healthReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExosEnclosureHealth {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ctrlAIp: ").append(toIndentedString(ctrlAIp)).append("\n");
    sb.append("    ctrlBIp: ").append(toIndentedString(ctrlBIp)).append("\n");
    sb.append("    health: ").append(toIndentedString(health)).append("\n");
    sb.append("    healthReason: ").append(toIndentedString(healthReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
