/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.24.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Default settings for EXOS enclosures
 */
@Schema(description = "Default settings for EXOS enclosures")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-18T06:34:31.141535853Z[Etc/UTC]")

public class ExosDefaults {
  @JsonProperty("username")
  private String username = null;

  @JsonProperty("username_env")
  private String usernameEnv = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("password_env")
  private String passwordEnv = null;

  public ExosDefaults username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public ExosDefaults usernameEnv(String usernameEnv) {
    this.usernameEnv = usernameEnv;
    return this;
  }

   /**
   * Get usernameEnv
   * @return usernameEnv
  **/
  @Schema(description = "")
  public String getUsernameEnv() {
    return usernameEnv;
  }

  public void setUsernameEnv(String usernameEnv) {
    this.usernameEnv = usernameEnv;
  }

  public ExosDefaults password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @Schema(description = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public ExosDefaults passwordEnv(String passwordEnv) {
    this.passwordEnv = passwordEnv;
    return this;
  }

   /**
   * Get passwordEnv
   * @return passwordEnv
  **/
  @Schema(description = "")
  public String getPasswordEnv() {
    return passwordEnv;
  }

  public void setPasswordEnv(String passwordEnv) {
    this.passwordEnv = passwordEnv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExosDefaults exosDefaults = (ExosDefaults) o;
    return Objects.equals(this.username, exosDefaults.username) &&
        Objects.equals(this.usernameEnv, exosDefaults.usernameEnv) &&
        Objects.equals(this.password, exosDefaults.password) &&
        Objects.equals(this.passwordEnv, exosDefaults.passwordEnv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, usernameEnv, password, passwordEnv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExosDefaults {\n");
    
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    usernameEnv: ").append(toIndentedString(usernameEnv)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    passwordEnv: ").append(toIndentedString(passwordEnv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
