/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InitAuthTokenRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class InitAuthTokenRequest {
  @JsonProperty("only_satellites")
  private Boolean onlySatellites = false;

  @JsonProperty("description")
  private String description = "init-client";

  @JsonProperty("no_https")
  private Boolean noHttps = false;

  public InitAuthTokenRequest onlySatellites(Boolean onlySatellites) {
    this.onlySatellites = onlySatellites;
    return this;
  }

   /**
   * Get onlySatellites
   * @return onlySatellites
  **/
  @Schema(required = true, description = "")
  public Boolean isOnlySatellites() {
    return onlySatellites;
  }

  public void setOnlySatellites(Boolean onlySatellites) {
    this.onlySatellites = onlySatellites;
  }

  public InitAuthTokenRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InitAuthTokenRequest noHttps(Boolean noHttps) {
    this.noHttps = noHttps;
    return this;
  }

   /**
   * Get noHttps
   * @return noHttps
  **/
  @Schema(description = "")
  public Boolean isNoHttps() {
    return noHttps;
  }

  public void setNoHttps(Boolean noHttps) {
    this.noHttps = noHttps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitAuthTokenRequest initAuthTokenRequest = (InitAuthTokenRequest) o;
    return Objects.equals(this.onlySatellites, initAuthTokenRequest.onlySatellites) &&
        Objects.equals(this.description, initAuthTokenRequest.description) &&
        Objects.equals(this.noHttps, initAuthTokenRequest.noHttps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(onlySatellites, description, noHttps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitAuthTokenRequest {\n");
    
    sb.append("    onlySatellites: ").append(toIndentedString(onlySatellites)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    noHttps: ").append(toIndentedString(noHttps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
