/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.22.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.LUKSVolume;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * LUKSResource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-02T13:40:09.628252133Z[Etc/UTC]")

public class LUKSResource {
  @JsonProperty("luks_volumes")
  private List<LUKSVolume> luksVolumes = null;

  public LUKSResource luksVolumes(List<LUKSVolume> luksVolumes) {
    this.luksVolumes = luksVolumes;
    return this;
  }

  public LUKSResource addLuksVolumesItem(LUKSVolume luksVolumesItem) {
    if (this.luksVolumes == null) {
      this.luksVolumes = new ArrayList<>();
    }
    this.luksVolumes.add(luksVolumesItem);
    return this;
  }

   /**
   * Get luksVolumes
   * @return luksVolumes
  **/
  @Schema(description = "")
  public List<LUKSVolume> getLuksVolumes() {
    return luksVolumes;
  }

  public void setLuksVolumes(List<LUKSVolume> luksVolumes) {
    this.luksVolumes = luksVolumes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LUKSResource luKSResource = (LUKSResource) o;
    return Objects.equals(this.luksVolumes, luKSResource.luksVolumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(luksVolumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LUKSResource {\n");
    
    sb.append("    luksVolumes: ").append(toIndentedString(luksVolumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
