/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ModifyAuthToken
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class ModifyAuthToken {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("ip_filter")
  private String ipFilter = null;

  @JsonProperty("is_active")
  private Boolean isActive = null;

  public ModifyAuthToken description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ModifyAuthToken ipFilter(String ipFilter) {
    this.ipFilter = ipFilter;
    return this;
  }

   /**
   * Get ipFilter
   * @return ipFilter
  **/
  @Schema(description = "")
  public String getIpFilter() {
    return ipFilter;
  }

  public void setIpFilter(String ipFilter) {
    this.ipFilter = ipFilter;
  }

  public ModifyAuthToken isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyAuthToken modifyAuthToken = (ModifyAuthToken) o;
    return Objects.equals(this.description, modifyAuthToken.description) &&
        Objects.equals(this.ipFilter, modifyAuthToken.ipFilter) &&
        Objects.equals(this.isActive, modifyAuthToken.isActive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, ipFilter, isActive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyAuthToken {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ipFilter: ").append(toIndentedString(ipFilter)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
