/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * NodeEvacuate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class NodeEvacuate {
  @JsonProperty("target")
  private List<String> target = null;

  @JsonProperty("do_not_target")
  private List<String> doNotTarget = null;

  public NodeEvacuate target(List<String> target) {
    this.target = target;
    return this;
  }

  public NodeEvacuate addTargetItem(String targetItem) {
    if (this.target == null) {
      this.target = new ArrayList<>();
    }
    this.target.add(targetItem);
    return this;
  }

   /**
   * List of nodes that are allowed to be used as evacuation-target
   * @return target
  **/
  @Schema(description = "List of nodes that are allowed to be used as evacuation-target")
  public List<String> getTarget() {
    return target;
  }

  public void setTarget(List<String> target) {
    this.target = target;
  }

  public NodeEvacuate doNotTarget(List<String> doNotTarget) {
    this.doNotTarget = doNotTarget;
    return this;
  }

  public NodeEvacuate addDoNotTargetItem(String doNotTargetItem) {
    if (this.doNotTarget == null) {
      this.doNotTarget = new ArrayList<>();
    }
    this.doNotTarget.add(doNotTargetItem);
    return this;
  }

   /**
   * List of nodes that are prohibited to be used as evacuation-target
   * @return doNotTarget
  **/
  @Schema(description = "List of nodes that are prohibited to be used as evacuation-target")
  public List<String> getDoNotTarget() {
    return doNotTarget;
  }

  public void setDoNotTarget(List<String> doNotTarget) {
    this.doNotTarget = doNotTarget;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeEvacuate nodeEvacuate = (NodeEvacuate) o;
    return Objects.equals(this.target, nodeEvacuate.target) &&
        Objects.equals(this.doNotTarget, nodeEvacuate.doNotTarget);
  }

  @Override
  public int hashCode() {
    return Objects.hash(target, doNotTarget);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeEvacuate {\n");
    
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    doNotTarget: ").append(toIndentedString(doNotTarget)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
