/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.24.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * NodeRestore
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-18T06:34:31.141535853Z[Etc/UTC]")

public class NodeRestore {
  @JsonProperty("delete_resources")
  private Boolean deleteResources = null;

  @JsonProperty("delete_snapshots")
  private Boolean deleteSnapshots = null;

  public NodeRestore deleteResources(Boolean deleteResources) {
    this.deleteResources = deleteResources;
    return this;
  }

   /**
   * Get deleteResources
   * @return deleteResources
  **/
  @Schema(description = "")
  public Boolean isDeleteResources() {
    return deleteResources;
  }

  public void setDeleteResources(Boolean deleteResources) {
    this.deleteResources = deleteResources;
  }

  public NodeRestore deleteSnapshots(Boolean deleteSnapshots) {
    this.deleteSnapshots = deleteSnapshots;
    return this;
  }

   /**
   * Get deleteSnapshots
   * @return deleteSnapshots
  **/
  @Schema(description = "")
  public Boolean isDeleteSnapshots() {
    return deleteSnapshots;
  }

  public void setDeleteSnapshots(Boolean deleteSnapshots) {
    this.deleteSnapshots = deleteSnapshots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeRestore nodeRestore = (NodeRestore) o;
    return Objects.equals(this.deleteResources, nodeRestore.deleteResources) &&
        Objects.equals(this.deleteSnapshots, nodeRestore.deleteSnapshots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteResources, deleteSnapshots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeRestore {\n");
    
    sb.append("    deleteResources: ").append(toIndentedString(deleteResources)).append("\n");
    sb.append("    deleteSnapshots: ").append(toIndentedString(deleteSnapshots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
