/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * NodeCreateEbs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class NodeCreateEbs {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("ebs_remote_name")
  private String ebsRemoteName = null;

  public NodeCreateEbs name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "nodeA", required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NodeCreateEbs ebsRemoteName(String ebsRemoteName) {
    this.ebsRemoteName = ebsRemoteName;
    return this;
  }

   /**
   * Get ebsRemoteName
   * @return ebsRemoteName
  **/
  @Schema(example = "EbsRemote", required = true, description = "")
  public String getEbsRemoteName() {
    return ebsRemoteName;
  }

  public void setEbsRemoteName(String ebsRemoteName) {
    this.ebsRemoteName = ebsRemoteName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeCreateEbs nodeCreateEbs = (NodeCreateEbs) o;
    return Objects.equals(this.name, nodeCreateEbs.name) &&
        Objects.equals(this.ebsRemoteName, nodeCreateEbs.ebsRemoteName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ebsRemoteName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeCreateEbs {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ebsRemoteName: ").append(toIndentedString(ebsRemoteName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
