/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.10.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.NVMEVolume;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * NVMEResource
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-31T11:02:45.596Z[GMT]")
public class NVMEResource {
  @JsonProperty("nvme_volumes")
  private List<NVMEVolume> nvmeVolumes = null;

  public NVMEResource nvmeVolumes(List<NVMEVolume> nvmeVolumes) {
    this.nvmeVolumes = nvmeVolumes;
    return this;
  }

  public NVMEResource addNvmeVolumesItem(NVMEVolume nvmeVolumesItem) {
    if (this.nvmeVolumes == null) {
      this.nvmeVolumes = new ArrayList<>();
    }
    this.nvmeVolumes.add(nvmeVolumesItem);
    return this;
  }

   /**
   * Get nvmeVolumes
   * @return nvmeVolumes
  **/
  @Schema(description = "")
  public List<NVMEVolume> getNvmeVolumes() {
    return nvmeVolumes;
  }

  public void setNvmeVolumes(List<NVMEVolume> nvmeVolumes) {
    this.nvmeVolumes = nvmeVolumes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NVMEResource nvMEResource = (NVMEResource) o;
    return Objects.equals(this.nvmeVolumes, nvMEResource.nvmeVolumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nvmeVolumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NVMEResource {\n");
    
    sb.append("    nvmeVolumes: ").append(toIndentedString(nvmeVolumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
