/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.6.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
* OneOfVolumeLayerData
*/
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "type"
)
@JsonSubTypes({
    @JsonSubTypes.Type(value = DrbdVolume.class, name = "DRBD"),
    @JsonSubTypes.Type(value = StorageVolume.class, name = "STORAGE"),
    @JsonSubTypes.Type(value = CacheVolume.class, name = "CACHE"),
    @JsonSubTypes.Type(value = LUKSVolume.class, name = "LUKS"),
    @JsonSubTypes.Type(value = NVMEVolume.class, name = "NVME"),
    @JsonSubTypes.Type(value = WritecacheVolume.class, name = "WRITECACHE")
})
public interface OneOfVolumeLayerData {

}
