/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.8.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ProviderKind
 */
public enum ProviderKind {
  DISKLESS("DISKLESS"),
  LVM("LVM"),
  LVM_THIN("LVM_THIN"),
  ZFS("ZFS"),
  ZFS_THIN("ZFS_THIN"),
  OPENFLEX_TARGET("OPENFLEX_TARGET"),
  FILE("FILE"),
  FILE_THIN("FILE_THIN"),
  SPDK("SPDK");

  private String value;

  ProviderKind(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ProviderKind fromValue(String text) {
    for (ProviderKind b : ProviderKind.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
