/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.24.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.AutoSelectFilter;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * QuerySizeInfoRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-18T06:34:31.141535853Z[Etc/UTC]")

public class QuerySizeInfoRequest {
  @JsonProperty("select_filter")
  private AutoSelectFilter selectFilter = null;

  @JsonProperty("ignore_cache_older_than_sec")
  private Integer ignoreCacheOlderThanSec = -1;

  public QuerySizeInfoRequest selectFilter(AutoSelectFilter selectFilter) {
    this.selectFilter = selectFilter;
    return this;
  }

   /**
   * Get selectFilter
   * @return selectFilter
  **/
  @Schema(description = "")
  public AutoSelectFilter getSelectFilter() {
    return selectFilter;
  }

  public void setSelectFilter(AutoSelectFilter selectFilter) {
    this.selectFilter = selectFilter;
  }

  public QuerySizeInfoRequest ignoreCacheOlderThanSec(Integer ignoreCacheOlderThanSec) {
    this.ignoreCacheOlderThanSec = ignoreCacheOlderThanSec;
    return this;
  }

   /**
   * Get ignoreCacheOlderThanSec
   * @return ignoreCacheOlderThanSec
  **/
  @Schema(description = "")
  public Integer getIgnoreCacheOlderThanSec() {
    return ignoreCacheOlderThanSec;
  }

  public void setIgnoreCacheOlderThanSec(Integer ignoreCacheOlderThanSec) {
    this.ignoreCacheOlderThanSec = ignoreCacheOlderThanSec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuerySizeInfoRequest querySizeInfoRequest = (QuerySizeInfoRequest) o;
    return Objects.equals(this.selectFilter, querySizeInfoRequest.selectFilter) &&
        Objects.equals(this.ignoreCacheOlderThanSec, querySizeInfoRequest.ignoreCacheOlderThanSec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectFilter, ignoreCacheOlderThanSec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuerySizeInfoRequest {\n");
    
    sb.append("    selectFilter: ").append(toIndentedString(selectFilter)).append("\n");
    sb.append("    ignoreCacheOlderThanSec: ").append(toIndentedString(ignoreCacheOlderThanSec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
