/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ReactorExecRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class ReactorExecRequest {
  @JsonProperty("nodes")
  private List<String> nodes = new ArrayList<>();

  @JsonProperty("resource")
  private String resource = null;

  @JsonProperty("wait")
  private Boolean wait = false;

  public ReactorExecRequest nodes(List<String> nodes) {
    this.nodes = nodes;
    return this;
  }

  public ReactorExecRequest addNodesItem(String nodesItem) {
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @Schema(required = true, description = "")
  public List<String> getNodes() {
    return nodes;
  }

  public void setNodes(List<String> nodes) {
    this.nodes = nodes;
  }

  public ReactorExecRequest resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * The resource name for evict operation
   * @return resource
  **/
  @Schema(description = "The resource name for evict operation")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public ReactorExecRequest wait(Boolean wait) {
    this.wait = wait;
    return this;
  }

   /**
   * For evict only: if true, the command runs synchronously and the response includes active_node (the node that took over). Use only when the evicted service is not the LINSTOR controller itself, as evicting the controller drops the satellite connection. 
   * @return wait
  **/
  @Schema(description = "For evict only: if true, the command runs synchronously and the response includes active_node (the node that took over). Use only when the evicted service is not the LINSTOR controller itself, as evicting the controller drops the satellite connection. ")
  public Boolean isWait() {
    return wait;
  }

  public void setWait(Boolean wait) {
    this.wait = wait;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReactorExecRequest reactorExecRequest = (ReactorExecRequest) o;
    return Objects.equals(this.nodes, reactorExecRequest.nodes) &&
        Objects.equals(this.resource, reactorExecRequest.resource) &&
        Objects.equals(this.wait, reactorExecRequest.wait);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodes, resource, wait);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReactorExecRequest {\n");
    
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    wait: ").append(toIndentedString(wait)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
