/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ReactorPluginRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class ReactorPluginRequest {
  @JsonProperty("nodes")
  private List<String> nodes = new ArrayList<>();

  @JsonProperty("config")
  private String config = null;

  @JsonProperty("now")
  private Boolean now = false;

  public ReactorPluginRequest nodes(List<String> nodes) {
    this.nodes = nodes;
    return this;
  }

  public ReactorPluginRequest addNodesItem(String nodesItem) {
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @Schema(required = true, description = "")
  public List<String> getNodes() {
    return nodes;
  }

  public void setNodes(List<String> nodes) {
    this.nodes = nodes;
  }

  public ReactorPluginRequest config(String config) {
    this.config = config;
    return this;
  }

   /**
   * The plugin config name (e.g., linstor_controller)
   * @return config
  **/
  @Schema(required = true, description = "The plugin config name (e.g., linstor_controller)")
  public String getConfig() {
    return config;
  }

  public void setConfig(String config) {
    this.config = config;
  }

  public ReactorPluginRequest now(Boolean now) {
    this.now = now;
    return this;
  }

   /**
   * For disable only: if true, also stops the drbd-services target immediately (equivalent to &#x27;drbd-reactorctl disable --now&#x27;). Defaults to false. 
   * @return now
  **/
  @Schema(description = "For disable only: if true, also stops the drbd-services target immediately (equivalent to 'drbd-reactorctl disable --now'). Defaults to false. ")
  public Boolean isNow() {
    return now;
  }

  public void setNow(Boolean now) {
    this.now = now;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReactorPluginRequest reactorPluginRequest = (ReactorPluginRequest) o;
    return Objects.equals(this.nodes, reactorPluginRequest.nodes) &&
        Objects.equals(this.config, reactorPluginRequest.config) &&
        Objects.equals(this.now, reactorPluginRequest.now);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodes, config, now);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReactorPluginRequest {\n");
    
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    now: ").append(toIndentedString(now)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
