/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ReplicationState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class ReplicationState {
  @JsonProperty("replication_state")
  private String replicationState = null;

  @JsonProperty("done_percentage")
  private Double donePercentage = null;

  public ReplicationState replicationState(String replicationState) {
    this.replicationState = replicationState;
    return this;
  }

   /**
   * Get replicationState
   * @return replicationState
  **/
  @Schema(description = "")
  public String getReplicationState() {
    return replicationState;
  }

  public void setReplicationState(String replicationState) {
    this.replicationState = replicationState;
  }

  public ReplicationState donePercentage(Double donePercentage) {
    this.donePercentage = donePercentage;
    return this;
  }

   /**
   * Get donePercentage
   * @return donePercentage
  **/
  @Schema(description = "")
  public Double getDonePercentage() {
    return donePercentage;
  }

  public void setDonePercentage(Double donePercentage) {
    this.donePercentage = donePercentage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicationState replicationState = (ReplicationState) o;
    return Objects.equals(this.replicationState, replicationState.replicationState) &&
        Objects.equals(this.donePercentage, replicationState.donePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(replicationState, donePercentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicationState {\n");
    
    sb.append("    replicationState: ").append(toIndentedString(replicationState)).append("\n");
    sb.append("    donePercentage: ").append(toIndentedString(donePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
