/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.24.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.ResourceDefinition;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ResourceDefinitionCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-18T06:34:31.141535853Z[Etc/UTC]")

public class ResourceDefinitionCreate {
  @JsonProperty("drbd_port")
  private Integer drbdPort = null;

  @JsonProperty("drbd_secret")
  private String drbdSecret = null;

  @JsonProperty("drbd_peer_slots")
  private Integer drbdPeerSlots = null;

  @JsonProperty("drbd_transport_type")
  private String drbdTransportType = null;

  @JsonProperty("resource_definition")
  private ResourceDefinition resourceDefinition = null;

  public ResourceDefinitionCreate drbdPort(Integer drbdPort) {
    this.drbdPort = drbdPort;
    return this;
  }

   /**
   * drbd port for resources
   * @return drbdPort
  **/
  @Schema(description = "drbd port for resources")
  public Integer getDrbdPort() {
    return drbdPort;
  }

  public void setDrbdPort(Integer drbdPort) {
    this.drbdPort = drbdPort;
  }

  public ResourceDefinitionCreate drbdSecret(String drbdSecret) {
    this.drbdSecret = drbdSecret;
    return this;
  }

   /**
   * drbd resource secret
   * @return drbdSecret
  **/
  @Schema(example = "7sqCWjvGmwAiV5kzg3VF", description = "drbd resource secret")
  public String getDrbdSecret() {
    return drbdSecret;
  }

  public void setDrbdSecret(String drbdSecret) {
    this.drbdSecret = drbdSecret;
  }

  public ResourceDefinitionCreate drbdPeerSlots(Integer drbdPeerSlots) {
    this.drbdPeerSlots = drbdPeerSlots;
    return this;
  }

   /**
   * drbd peer slot number
   * @return drbdPeerSlots
  **/
  @Schema(description = "drbd peer slot number")
  public Integer getDrbdPeerSlots() {
    return drbdPeerSlots;
  }

  public void setDrbdPeerSlots(Integer drbdPeerSlots) {
    this.drbdPeerSlots = drbdPeerSlots;
  }

  public ResourceDefinitionCreate drbdTransportType(String drbdTransportType) {
    this.drbdTransportType = drbdTransportType;
    return this;
  }

   /**
   * Get drbdTransportType
   * @return drbdTransportType
  **/
  @Schema(example = "IP", description = "")
  public String getDrbdTransportType() {
    return drbdTransportType;
  }

  public void setDrbdTransportType(String drbdTransportType) {
    this.drbdTransportType = drbdTransportType;
  }

  public ResourceDefinitionCreate resourceDefinition(ResourceDefinition resourceDefinition) {
    this.resourceDefinition = resourceDefinition;
    return this;
  }

   /**
   * Get resourceDefinition
   * @return resourceDefinition
  **/
  @Schema(required = true, description = "")
  public ResourceDefinition getResourceDefinition() {
    return resourceDefinition;
  }

  public void setResourceDefinition(ResourceDefinition resourceDefinition) {
    this.resourceDefinition = resourceDefinition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceDefinitionCreate resourceDefinitionCreate = (ResourceDefinitionCreate) o;
    return Objects.equals(this.drbdPort, resourceDefinitionCreate.drbdPort) &&
        Objects.equals(this.drbdSecret, resourceDefinitionCreate.drbdSecret) &&
        Objects.equals(this.drbdPeerSlots, resourceDefinitionCreate.drbdPeerSlots) &&
        Objects.equals(this.drbdTransportType, resourceDefinitionCreate.drbdTransportType) &&
        Objects.equals(this.resourceDefinition, resourceDefinitionCreate.resourceDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(drbdPort, drbdSecret, drbdPeerSlots, drbdTransportType, resourceDefinition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceDefinitionCreate {\n");
    
    sb.append("    drbdPort: ").append(toIndentedString(drbdPort)).append("\n");
    sb.append("    drbdSecret: ").append(toIndentedString(drbdSecret)).append("\n");
    sb.append("    drbdPeerSlots: ").append(toIndentedString(drbdPeerSlots)).append("\n");
    sb.append("    drbdTransportType: ").append(toIndentedString(drbdTransportType)).append("\n");
    sb.append("    resourceDefinition: ").append(toIndentedString(resourceDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
