/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.28.0
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.AutoSelectFilter;
import com.linbit.linstor.api.model.Properties;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ResourceGroupModify
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-29T10:05:03.218384239Z[Etc/UTC]")

public class ResourceGroupModify {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("override_props")
  private Properties overrideProps = null;

  @JsonProperty("delete_props")
  private List<String> deleteProps = null;

  @JsonProperty("delete_namespaces")
  private List<String> deleteNamespaces = null;

  @JsonProperty("select_filter")
  private AutoSelectFilter selectFilter = null;

  @JsonProperty("peer_slots")
  private Integer peerSlots = null;

  @JsonProperty("snap_names")
  private List<String> snapNames = null;

  @JsonProperty("copy_all_snaps")
  private Boolean copyAllSnaps = null;

  public ResourceGroupModify description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ResourceGroupModify overrideProps(Properties overrideProps) {
    this.overrideProps = overrideProps;
    return this;
  }

   /**
   * Get overrideProps
   * @return overrideProps
  **/
  @Schema(description = "")
  public Properties getOverrideProps() {
    return overrideProps;
  }

  public void setOverrideProps(Properties overrideProps) {
    this.overrideProps = overrideProps;
  }

  public ResourceGroupModify deleteProps(List<String> deleteProps) {
    this.deleteProps = deleteProps;
    return this;
  }

  public ResourceGroupModify addDeletePropsItem(String deletePropsItem) {
    if (this.deleteProps == null) {
      this.deleteProps = new ArrayList<>();
    }
    this.deleteProps.add(deletePropsItem);
    return this;
  }

   /**
   * Get deleteProps
   * @return deleteProps
  **/
  @Schema(description = "")
  public List<String> getDeleteProps() {
    return deleteProps;
  }

  public void setDeleteProps(List<String> deleteProps) {
    this.deleteProps = deleteProps;
  }

  public ResourceGroupModify deleteNamespaces(List<String> deleteNamespaces) {
    this.deleteNamespaces = deleteNamespaces;
    return this;
  }

  public ResourceGroupModify addDeleteNamespacesItem(String deleteNamespacesItem) {
    if (this.deleteNamespaces == null) {
      this.deleteNamespaces = new ArrayList<>();
    }
    this.deleteNamespaces.add(deleteNamespacesItem);
    return this;
  }

   /**
   * Get deleteNamespaces
   * @return deleteNamespaces
  **/
  @Schema(description = "")
  public List<String> getDeleteNamespaces() {
    return deleteNamespaces;
  }

  public void setDeleteNamespaces(List<String> deleteNamespaces) {
    this.deleteNamespaces = deleteNamespaces;
  }

  public ResourceGroupModify selectFilter(AutoSelectFilter selectFilter) {
    this.selectFilter = selectFilter;
    return this;
  }

   /**
   * Get selectFilter
   * @return selectFilter
  **/
  @Schema(description = "")
  public AutoSelectFilter getSelectFilter() {
    return selectFilter;
  }

  public void setSelectFilter(AutoSelectFilter selectFilter) {
    this.selectFilter = selectFilter;
  }

  public ResourceGroupModify peerSlots(Integer peerSlots) {
    this.peerSlots = peerSlots;
    return this;
  }

   /**
   * Get peerSlots
   * @return peerSlots
  **/
  @Schema(description = "")
  public Integer getPeerSlots() {
    return peerSlots;
  }

  public void setPeerSlots(Integer peerSlots) {
    this.peerSlots = peerSlots;
  }

  public ResourceGroupModify snapNames(List<String> snapNames) {
    this.snapNames = snapNames;
    return this;
  }

  public ResourceGroupModify addSnapNamesItem(String snapNamesItem) {
    if (this.snapNames == null) {
      this.snapNames = new ArrayList<>();
    }
    this.snapNames.add(snapNamesItem);
    return this;
  }

   /**
   * Get snapNames
   * @return snapNames
  **/
  @Schema(description = "")
  public List<String> getSnapNames() {
    return snapNames;
  }

  public void setSnapNames(List<String> snapNames) {
    this.snapNames = snapNames;
  }

  public ResourceGroupModify copyAllSnaps(Boolean copyAllSnaps) {
    this.copyAllSnaps = copyAllSnaps;
    return this;
  }

   /**
   * Get copyAllSnaps
   * @return copyAllSnaps
  **/
  @Schema(description = "")
  public Boolean isCopyAllSnaps() {
    return copyAllSnaps;
  }

  public void setCopyAllSnaps(Boolean copyAllSnaps) {
    this.copyAllSnaps = copyAllSnaps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceGroupModify resourceGroupModify = (ResourceGroupModify) o;
    return Objects.equals(this.description, resourceGroupModify.description) &&
        Objects.equals(this.overrideProps, resourceGroupModify.overrideProps) &&
        Objects.equals(this.deleteProps, resourceGroupModify.deleteProps) &&
        Objects.equals(this.deleteNamespaces, resourceGroupModify.deleteNamespaces) &&
        Objects.equals(this.selectFilter, resourceGroupModify.selectFilter) &&
        Objects.equals(this.peerSlots, resourceGroupModify.peerSlots) &&
        Objects.equals(this.snapNames, resourceGroupModify.snapNames) &&
        Objects.equals(this.copyAllSnaps, resourceGroupModify.copyAllSnaps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, overrideProps, deleteProps, deleteNamespaces, selectFilter, peerSlots, snapNames, copyAllSnaps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceGroupModify {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    overrideProps: ").append(toIndentedString(overrideProps)).append("\n");
    sb.append("    deleteProps: ").append(toIndentedString(deleteProps)).append("\n");
    sb.append("    deleteNamespaces: ").append(toIndentedString(deleteNamespaces)).append("\n");
    sb.append("    selectFilter: ").append(toIndentedString(selectFilter)).append("\n");
    sb.append("    peerSlots: ").append(toIndentedString(peerSlots)).append("\n");
    sb.append("    snapNames: ").append(toIndentedString(snapNames)).append("\n");
    sb.append("    copyAllSnaps: ").append(toIndentedString(copyAllSnaps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
