/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * VolumeDefinitionModifyPassphrase
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class VolumeDefinitionModifyPassphrase {
  @JsonProperty("new_passphrase")
  private String newPassphrase = null;

  public VolumeDefinitionModifyPassphrase newPassphrase(String newPassphrase) {
    this.newPassphrase = newPassphrase;
    return this;
  }

   /**
   * Get newPassphrase
   * @return newPassphrase
  **/
  @Schema(required = true, description = "")
  public String getNewPassphrase() {
    return newPassphrase;
  }

  public void setNewPassphrase(String newPassphrase) {
    this.newPassphrase = newPassphrase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeDefinitionModifyPassphrase volumeDefinitionModifyPassphrase = (VolumeDefinitionModifyPassphrase) o;
    return Objects.equals(this.newPassphrase, volumeDefinitionModifyPassphrase.newPassphrase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newPassphrase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeDefinitionModifyPassphrase {\n");
    
    sb.append("    newPassphrase: ").append(toIndentedString(newPassphrase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
