/*
 * Linstor REST API
 *
 *
 * OpenAPI spec version: 1.25.1
 * Contact: rene.peinthor@linbit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.linbit.linstor.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.linbit.linstor.api.model.ReplicationStates;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * VolumeState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-08T11:58:50.875992750Z[Etc/UTC]")

public class VolumeState {
  @JsonProperty("disk_state")
  private String diskState = null;

  @JsonProperty("replication_states")
  private ReplicationStates replicationStates = null;

  public VolumeState diskState(String diskState) {
    this.diskState = diskState;
    return this;
  }

   /**
   * Get diskState
   * @return diskState
  **/
  @Schema(description = "")
  public String getDiskState() {
    return diskState;
  }

  public void setDiskState(String diskState) {
    this.diskState = diskState;
  }

  public VolumeState replicationStates(ReplicationStates replicationStates) {
    this.replicationStates = replicationStates;
    return this;
  }

   /**
   * Get replicationStates
   * @return replicationStates
  **/
  @Schema(description = "")
  public ReplicationStates getReplicationStates() {
    return replicationStates;
  }

  public void setReplicationStates(ReplicationStates replicationStates) {
    this.replicationStates = replicationStates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeState volumeState = (VolumeState) o;
    return Objects.equals(this.diskState, volumeState.diskState) &&
        Objects.equals(this.replicationStates, volumeState.replicationStates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(diskState, replicationStates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeState {\n");
    
    sb.append("    diskState: ").append(toIndentedString(diskState)).append("\n");
    sb.append("    replicationStates: ").append(toIndentedString(replicationStates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
